apiVersion: v1
kind: ConfigMap
metadata:
  name: aqm-postgres-config
data:
  # DB connection strings
  # Should match DB_USER and DB_NAME in collector-configmap.yaml
  POSTGRES_USER: aqm_app
  POSTGRES_DB: air_quality_monitor
